[profile.default]
optimizer = true
optimizer-runs = 1
src = 'solidity/contracts'
out = 'out'
libs = ['node_modules']
test = 'solidity/tests'
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
bsc_mainnet = "${BSC_RPC_URL}"

