[profile.default]
optimizer = true
optimizer-runs = 1
src = 'solidity/contracts'
out = 'out'
cache_path = './forge_cache'
libs = ["node_modules", "lib"]
test = 'solidity/tests'
fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true
solc = "0.8.19"


[rpc_endpoints]
bsc_mainnet = "${BSC_RPC_URL}"

[etherscan]
bsc = { key = "${BSC_SCAN_API_KEY}", url = "https://api.bscscan.com/api" }
